// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SmartRancho.API.Data;

#nullable disable

namespace SmartRancho.API.Migrations
{
    [DbContext(typeof(SmartRanchoDbContext))]
    [Migration("20260423210915_AddIdentityTables")]
    partial class AddIdentityTables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SmartRancho.API.Entities.Animal", b =>
                {
                    b.Property<int>("AnimalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AnimalId"));

                    b.Property<string>("Color")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("FechaNacimiento")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime2");

                    b.Property<string>("FotoUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumeroArete")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Observaciones")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PotreroId")
                        .HasColumnType("int");

                    b.Property<int>("RanchoId")
                        .HasColumnType("int");

                    b.Property<string>("Raza")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sexo")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AnimalId");

                    b.HasIndex("PotreroId");

                    b.HasIndex("RanchoId", "NumeroArete")
                        .IsUnique()
                        .HasDatabaseName("UX_Animal_Rancho_Arete");

                    b.ToTable("Animales");
                });

            modelBuilder.Entity("SmartRancho.API.Entities.EstadoAnimal", b =>
                {
                    b.Property<int>("EstadoAnimalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EstadoAnimalId"));

                    b.Property<int>("AnimalId")
                        .HasColumnType("int");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaEstado")
                        .HasColumnType("datetime2");

                    b.Property<string>("Motivo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("PrecioVenta")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("EstadoAnimalId");

                    b.HasIndex("AnimalId");

                    b.ToTable("EstadoAnimal");
                });

            modelBuilder.Entity("SmartRancho.API.Entities.Potrero", b =>
                {
                    b.Property<int>("PotreroId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PotreroId"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RanchoId")
                        .HasColumnType("int");

                    b.Property<decimal?>("TamanoHectareas")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("PotreroId");

                    b.HasIndex("RanchoId");

                    b.ToTable("Potreros");
                });

            modelBuilder.Entity("SmartRancho.API.Entities.Rancho", b =>
                {
                    b.Property<int>("RanchoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RanchoId"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("EmailContacto")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime2");

                    b.Property<string>("NombreRancho")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Propietario")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefono")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RanchoId");

                    b.ToTable("Ranchos");
                });

            modelBuilder.Entity("SmartRancho.API.Entities.Usuario", b =>
                {
                    b.Property<int>("UsuarioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UsuarioId"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RanchoId")
                        .HasColumnType("int");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UsuarioId");

                    b.HasIndex("RanchoId");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("SmartRancho.API.Entities.Animal", b =>
                {
                    b.HasOne("SmartRancho.API.Entities.Potrero", "Potrero")
                        .WithMany("Animales")
                        .HasForeignKey("PotreroId");

                    b.HasOne("SmartRancho.API.Entities.Rancho", "Rancho")
                        .WithMany("Animales")
                        .HasForeignKey("RanchoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Potrero");

                    b.Navigation("Rancho");
                });

            modelBuilder.Entity("SmartRancho.API.Entities.EstadoAnimal", b =>
                {
                    b.HasOne("SmartRancho.API.Entities.Animal", "Animal")
                        .WithMany("Estados")
                        .HasForeignKey("AnimalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Animal");
                });

            modelBuilder.Entity("SmartRancho.API.Entities.Potrero", b =>
                {
                    b.HasOne("SmartRancho.API.Entities.Rancho", "Rancho")
                        .WithMany("Potreros")
                        .HasForeignKey("RanchoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rancho");
                });

            modelBuilder.Entity("SmartRancho.API.Entities.Usuario", b =>
                {
                    b.HasOne("SmartRancho.API.Entities.Rancho", "Rancho")
                        .WithMany("Usuarios")
                        .HasForeignKey("RanchoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rancho");
                });

            modelBuilder.Entity("SmartRancho.API.Entities.Animal", b =>
                {
                    b.Navigation("Estados");
                });

            modelBuilder.Entity("SmartRancho.API.Entities.Potrero", b =>
                {
                    b.Navigation("Animales");
                });

            modelBuilder.Entity("SmartRancho.API.Entities.Rancho", b =>
                {
                    b.Navigation("Animales");

                    b.Navigation("Potreros");

                    b.Navigation("Usuarios");
                });
#pragma warning restore 612, 618
        }
    }
}
